apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: test-edb
spec:

  instances: 4
  minSyncReplicas: 1
  maxSyncReplicas: 2

  postgresql:
    parameters:
      shared_buffers: "256MB"

  storage:
    size: 1Gi
---
apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Pooler
metadata:
  name: pooler-example-rw
spec:
  cluster:
    name: test-edb

  instances: 2
  type: rw
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "1000"
      default_pool_size: "10"

